### ISSUE TITLE
convert_from_path not working on 18.04

### ISSUE THREAD

**Issue by dmathijs** [Belval/pdf2image#104]
Locally I'm developping my application on windows 10, when porting it to an ubuntu 18.04 production instance the convert_from_path function fails with the error: Unable to get page count. Is poppler installed and in Path?
I can correctly activate my python virtual environment and running pdfInfo against the specific file gives me the correct and expected information. Both poppler-utils and -data have been installed.

```
            with tempfile.TemporaryDirectory() as temp_dir:
                # convert pdf to multiple image FAILS HERE
                images = convert_from_path(_pdfPath, first_page=0, last_page=1, output_folder=temp_dir)
                
                # save images to temporary directory
                temp_images = []
                for i in range(len(images)):
                    image_path = f'{temp_dir}/{i}.jpg'
                    images[i].save(image_path, 'JPEG')
                    temp_images.append(image_path)

```
**To Reproduce**
To set up my flask application I followed this tutorial: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uswgi-and-nginx-on-ubuntu-18-04
Doing a simple request to my flask application which has a route that uses the convert_from_path function fails with the error mentioned above.

**Expected behavior**
The convert_from_path function should not fail with the error above if all correct libraries have been installed.

**Desktop (please complete the following information):**
- Ubuntu 18.04

**Additional context**
Running a flask application using uwsgi + nginx

**Comment by Belval** [comment]
Thank you for thoroughly filling the issue template, it helps a lot with troubleshooting.

If you don't mind getting your hands slightly dirty, edit https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L358 to print the exception instead of the hardcoded error message. This might help us pin-pointing the issue.

You can edit the package straight from your virtual environment.

Another thing to test is if it works when you are not using the `/tmp/` directory. Some companies lock them down and it causes `pdf2image` to behave strangely.

On one rare occurence, `pdfinfo` was not working due to a locale mismatch that added non-latin characters to the output which where then parsed by the non UTF-8 version of Python. This is a rather long shot but it can happen.

Finally, was it a specific PDF file that failed or all of them?

**Comment by dmathijs** [comment]
Hi,

I've edited the code and the error that is thrown is [Errno 2] No such file or directory: 'pdfinfo':'pdfinfo'.

I've tried using both a /tmp/ directory and not using it, both times it failed.
This issue persists for all types of pdfs, I tried 10 different ones, none of them are secured, all of them are just simple pdfs I found online.

**Comment by Belval** [comment]
Then the culprit is uWSGI probably isolating your OS dependencies, there seems to be a lot of gotchas when using uWSGI so you might want to check if any of these apply to your usecase: https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html

Also (if that dependency is self-imposed) you could give Gunicorn a try, it replaces uWSGI and I never had any issue with it.

**Comment by dmathijs** [comment]
So, 
I've been tinkering around. Installing Gunicorn didn't actually do anything. I started debugging and tried adding the poppler_path variable. That actually worked.
So it seems like for some reason I can't execute the pdfinfo command in the context of my flask application. Any idea how this could happen?

**Comment by Belval** [comment]
I have not seen that issue before, if you do find the reason please report back so it may help others.

**Comment by dmathijs** [comment]
Will do! 
Thanks for the quick help! ;)
