### ISSUE TITLE
The result image is missing some texts from the original pdf

### ISSUE THREAD

**Issue by LaTournesol** [Belval/pdf2image#107]
**Describe the bug**
Hi, I was using convert_from_path to convert a pdf, but the result image is only partially converted, I have tried on quite a few similar pdfs but only this one yields a partially converted image.

**To Reproduce**
Just use the convert_from_path function on the pdf that I'll email to you.

**Expected behavior**
Pdf will be partially converted to image.

**Screenshots**
I'll sent you the screenshots in the email because I don't want to publically upload the pdf,

**Desktop (please complete the following information):**
Windows Server 2016, 
pdf2image version 1.9.0

**Additional context**

**Comment by Belval** [comment]
I received your email and the aforementioned PDF, I'll have a look.

**Comment by Belval** [comment]
The error is caused by a missing font on your system. Try and convert it from Windows' cmd.exe and look at the logs it gives you (`pdftoppm -r 200 -jpeg your_pdf.pdf out`).

For example, I got: `Missing language pack for 'Adobe-GB1' mapping` 

Which was caused by my maching not having `poppler-data` installed. Once added to my system, I was able to convert it without any issues.

**Comment by LaTournesol** [comment]
Thank you so much for the timely response!

**Comment by amarchheda** [comment]
@Belval I am facing the same issue. While I try to run this on AWS Lambda. 
I build the libraries using yum install poppler-utils on AWS Linux AMI and use the results in the Zip field. 
The output image is attached. I would not be able to Upload the original PDF due to privacy issues. But it just has text in addition to the format that you see here. 
![image](https://user-images.githubusercontent.com/59660120/98315125-1eae5480-1f9d-11eb-904a-8214a5f44520.jpeg)

**Comment by Belval** [comment]
From the top of my head I'd say this is caused by missing fonts on the machine that runs pdf2image.

PDF don't usually embed their font (unless they use one of the default one OR follow the PDF/A spec). If you install a few fonts on lambda before running you will probably fix the error. Aside from that you can try and replicate the lambda environment in a container and run `pdftoppm` on your PDF file. Usually there will be warnings that will tell you exactly what's wrong.

Sorry if I can't be of much more help than that.

**Comment by amarchheda** [comment]
@Belval Thank you for your prompt reply! I did go through one of your other threads where you have a more detailed description of this. It surely is the Fonts that is messed up. I am still trying to figure out how to get Fonts working with AWS Lambda, but I am sure that would fix this. 

Would you happen to know where (path) does pdftoppm search for fonts?

**Comment by Belval** [comment]
Font paths are usually set by environment variable. See: https://stackoverflow.com/a/51622335

**Comment by amarchheda** [comment]
Yes! Thank you for the link, I was able to read through the same and get it done. <3 

Finally got around implementing this! :) Thank you for all the help.
