### ISSUE TITLE
Can't work some pdf files

### ISSUE THREAD

**Issue by chitra-star** [Belval/pdf2image#137]
![BAS16P11300049008_005-page-001](https://user-images.githubusercontent.com/52459438/80301079-91a16c00-87bf-11ea-8f69-2b8afe32c5d0.jpg)
Hi..I have more than 100pdf files but it's not working I don't know how it's happening..I attached one of my pdf files..I used python 3.8 .can you give any suggestions?

**Comment by Belval** [comment]
Can you describe what is not working? Do you have a stack trace?

**Comment by chitra-star** [comment]
That pdftoopm will opening more than half hour but it's didn't write output file.
I have attached one my pdf file..can you check that file?

**Comment by chitra-star** [comment]
That program ran but it's not writing output file it's happened for one set of files only.

**Comment by Belval** [comment]
Are you able to convert it manually with `pdftoppm`?

Also can you provide a code snippet of what you are doing.

**Comment by chitra-star** [comment]
No can't convert..this code only am using..

from pdf2image import convert_from_path
pages = convert_from_path('pdf_file', 500)
for page in pages:
    page.save('out.jpg', 'JPEG')

**Comment by chitra-star** [comment]
Can you tell me how to convert manually?

**Comment by Belval** [comment]
Use `pdftoppm -r 200 your_file.pdf out`.

Also, I can't see your attached PDF.

**Comment by chitra-star** [comment]
No can't convert...pls send ur mail id..I will send..
![BAS16P11300049008_005-page-001](https://user-images.githubusercontent.com/52459438/80331574-05964f80-8866-11ea-9423-2d1e26043302.jpg)
Now can you see my pdf?

**Comment by Belval** [comment]
Unfortunately no, GitHub renders it as a jpeg.

You can send the file at github@belval.org

**Comment by chitra-star** [comment]
I sent mail..

**Comment by chitra-star** [comment]
Pls try that pdf and tell the result..hope

**Comment by chitra-star** [comment]
Pls try that pdf and tell the result..hope

**Comment by chitra-star** [comment]
Did you try that pdf?

**Comment by Belval** [comment]
See my reply to your email.

**Comment by Belval** [comment]
I was not able to reproduce the issue, the conversion worked on my computer. Your issue is that this PDF is incredibly complex with very fine detail rendered with embedded geometries.

That being said, I found that using `fmt='jpeg'` or `fmt='png'` was much faster than the default format. `pdftocairo` was also faster so I will add a parameter to force pdftocairo use.

**Comment by chitra-star** [comment]
Thank you so much.. any other way to convert this pdf?

**Comment by Belval** [comment]
Well if you convert with `use_pdftocairo=True` (once merged), the conversion should be about three times faster.

**Comment by Belval** [comment]
I also noticed that your file is pretty big, so you might want to use `size=(2000,None)` or something like that to bring it back to a more reasonable size. It will go faster.

**Comment by chitra-star** [comment]
I tried but I can't convert..can you please explain?

**Comment by Belval** [comment]
Ok so when you convert, `pdf2image` has to use a rasterizer to convert what you see when you open your PDF into an image (JPEG, PNG, PPM, etc...). In your case, your image is gigantic, at almost 28 megapixels. Now the rasterizer has to process all that data and then package it into a file format. To give you an idea of the scale, your image when converted on my machine is 128MB, which is huge.

Now you have two options (that you can combine for maximum speed):

1. Convert your PDF with `convert_from_path("your_file.pdf", use_pdftocairo=True)` this will use a different rasterizer and be about three times faster. (**not merged**)
2. Convert your PDF with `convert_from_path("your_file.pdf", size=(2000,None))` this will scale the width of your image to 2000, while also scaling the height to a matching ratio.

Option 1 is not merged yet, because I have to run some tests to make sure that it works as expected.

**Comment by Belval** [comment]
Version 1.13.0 is released and includes the new `use_pdftocairo` parameter. Make sure to install it with `pip3 install pdf2image==1.13.0`.

**Comment by chitra-star** [comment]
Can't download this version

**Comment by Belval** [comment]
What is the error that you get?

**Comment by Belval** [comment]
Nevermind, there seems to be an error with the previous version I uploaded. The pip mirrors should update shortly.

**Comment by chitra-star** [comment]
I tried 2 option..o
While using option 1 I got unexpected keyword argument..while using option
1 I got same issue..it's did not return output file.. really I don't know
what I do..any other option is there or not?

**Comment by chitra-star** [comment]
Okay I will try after some times..

**Comment by chitra-star** [comment]
While installing this version of pdf2image I got could not find the version
that satisfies the requirements error.

**Comment by Belval** [comment]
It should be updated now.

**Comment by chitra-star** [comment]
Now it's converted..thanks..
