### ISSUE TITLE
convert_from_path generates all white images from non-empty PDF

### ISSUE THREAD

**Issue by baldesco** [Belval/pdf2image#167]
The library and the function `convert_from_path` in general work well, but with one particular PDF file I can't get the image files from the file pages. I get all empty white images, despite the fact that the file contains text.

This is the code that I'm using:

```
from pdf2image import convert_from_path
temp_dir = 'temp/'
pdf_path = 'in/73275.pdf'
pages = convert_from_path(pdf_path, output_folder=temp_dir)
counter = 0
for page in pages[:5]:
    counter += 1
    page_file = temp_dir + "/page_" + str(counter).zfill(7) + ".jpg"
    page.save(page_file, 'JPEG')
```

The file that I'm having trouble with can be downloaded from [here](https://www.dropbox.com/s/tekbf4kfyu8r5za/73275.pdf?dl=0):

Any idea of why this may be happening? I tried different values for the function's parameters, but the result is the same.

**Comment by ooojpeg** [comment]
I have looked into this but cannot repeat the same issue on Ubuntu using the latest version. Are you running this on Linux or Windows?

I used a direct copy of your code provided above.

**Comment by ThatIsAPseudo** [comment]
I've got the same issue by trying any code snippet on the pypi page. Some pdf results in white pages, another just has black background instead of all images (text is fine). Btw I'm on macOS, using conda.

**Comment by Belval** [comment]
> I've got the same issue by trying any code snippet on the pypi page, and with this code. Some pdf results in white pages, another just has black background instead of all images (text is fine). Btw I'm on macOS, using conda.

Can you provide the PDF files?

**Comment by ThatIsAPseudo** [comment]
> Can you provide the PDF files ?

As several of them are under copyright, I prefer to send it to you directly. Is the email adress on your Github profile fine ?

**Comment by Belval** [comment]
Yes.

**Comment by Belval** [comment]
@ThatIsAPseudo I am able to convert the files you sent me with the latest version of `pdf2image` on Ubuntu 20.04. Unfortunately I don't own a Mac to test but I would venture that the issue is with the libraries available on your machine. I saw that you used the png format to convert, you could try converting to PPM and using pillow to write the png files. This would avoid any possible issues with libpng on your system.

**Comment by brendendetels** [comment]
@Belval - I am having a similar issue on Windows 10 with code very similar to the one posted above. Actually, the entire PDF turns out blank except for a small portion of one page(The small portion that works appears to be in a different font). I have the latest version of pdf2image(1.13.1). Has a solution for this been found?

**Comment by brendendetels** [comment]
Update: Found the issue. I updated the version of poppler from 0.68.0 to 20.12.1.  I can't explain why this is the issue but it is now working.
