### ISSUE TITLE
pdf2image Increased text and border spacing

### ISSUE THREAD

**Issue by edgeTurbo** [Belval/pdf2image#236]
Increased text and border spacing
the code:
```
pages = convert_from_path(inpath, 500, size=(1300, 1500))
    pagecount = 1
    for page in pages:
        outputname = '%s/%s.png' % (imgsdir, pagecount)
        m_ls.append(outputname)
        page.save(outputname, 'PNG')
        pagecount += 1
```
the result:
![75961657190068_ pic](https://user-images.githubusercontent.com/104041263/177903776-6e98d007-3c6b-473e-9838-4d4aa93932f9.jpg)

**Comment by edgeTurbo** [comment]
[test2.pdf.zip](https://github.com/Belval/pdf2image/files/9068410/test2.pdf.zip)
the pdf demo ,thanks

**Comment by edgeTurbo** [comment]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/104041263/177944877-aa3d15ae-378f-498f-9a45-d1c58255ec60.png">

**Comment by Belval** [comment]
This issue is caused by the mediabox not being the same as the cropbox. If you always want to use the cropbox you can add `use_cropbox=True` to your function call. 

Without:
![without](https://user-images.githubusercontent.com/5399488/182249966-8c801e6d-dfbc-4188-adf9-c0531ae93504.png)

With: 

![with](https://user-images.githubusercontent.com/5399488/182249981-08c3d0e5-06e4-4d93-aa53-7a19f75c2571.png)
