### ISSUE TITLE
How to get transparent outputs background

### ISSUE THREAD

**Issue by ZZZZh** [Belval/pdf2image#39]
Is there any function that can choose the outputs background color to be transparent or in original color? Thanks !!

**Comment by Belval** [comment]
Can you give me a sample of what you want to do?

**Comment by ZZZZh** [comment]
![white](https://user-images.githubusercontent.com/11428907/50199735-85b4c700-038d-11e9-9ae4-b7f6b055fdc3.png)
![transparent](https://user-images.githubusercontent.com/11428907/50199736-864d5d80-038d-11e9-94e2-bc725a5126e5.png)
The first pic has original background color and the second one is transparent.

**Comment by Belval** [comment]
pdftoppm has the `-transp` option. I'll add a parameter to pdf2image for it.

**Comment by Belval** [comment]
My mistake, pdftocairo has the -transp option. Since it comes with poppler I could probably just swap backends without breaking anything, but that requires a bit more work and thought.

I'll keep you updated

**Comment by Belval** [comment]
You can now use the `transparent=True` option to get the output outlined above.

**Comment by ZZZZh** [comment]
It seems that transparent function not works. `transparent=True` returns an empty images list. Could you have a look, thanks.

**Comment by Belval** [comment]
The feature does work on my end, but I found a caveat with the implementation.

Instead of defaulting to `transparent=False` when the format does not support transparent images, pdf2image returns an empty list.

The expected behavior would be to get a list of not transparent images. This will be fixed in version 1.4.0.

In the meantime, you can use transparency with `convert_from_path('/your/path/here.pdf', fmt='png', transparent=True)`

**Comment by ZZZZh** [comment]
Yeah, it's working after I define the fmt parameter. Thank you.

**Comment by Belval** [comment]
Closing as this was fixed in 1.4.0.
