### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by BackEndTea** [Belval/pdf2image#57]
**Describe the bug**
When a real big pdf is converted to images, i run into an OSError: `OSError: [Errno 24] Too many open files ...`

**To Reproduce**
Run pdf2image on a real big pdf (e.g. 7.000 pages)

**Expected behavior**
Since i specified the output folder, i expected the images to be there, without all of them being loaded, and their file pointers to be closed.

**Comment by Belval** [comment]
That is caused by the OS, and not by pdf2image.

Under Linux I think you can increase the max open file count with `ulimit -n 100000`. See https://unix.stackexchange.com/questions/36841/why-is-number-of-open-files-limited-in-linux

**Comment by Belval** [comment]
Closing for no response. Feel free to reopen.

**Comment by jaidevd** [comment]
@Belval While the OS does restrict the number of open files for any process, I believe that simply increasing that limit is not a solution - especially since `pdf2image` can itself do something to close files.

For example, in [`pdf2image._load_output_folder`](https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L646), we have open PIL images but we haven't closed them. In [ine 659](https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L659), we're doing the following:

```python
images.append(Image.open(os.path.join(output_folder, f)))
```

Instead, we can do the following:
```python
with Image.open(os.path.join(output_folder, f)) as image:
    images.append(image)
```

This will ensure that the file is closed off.

What do you think?
